const IMAGE_URL=process.env.PUBLIC_URL;
export const Images = {
  LOGIN: IMAGE_URL + "/img/login.png",
  DESKTOP: IMAGE_URL + "/img/Desktop.png",
  MONITOR: IMAGE_URL + "/img/Monitor.png",
  PHONE: IMAGE_URL + "/img/Phone.png",
  TABLET: IMAGE_URL + "/img/Tablet.png",
  ICON: IMAGE_URL + "/img/No1.png",
  REVIEW: IMAGE_URL + "/img/001-review.png",
  USERS: IMAGE_URL + "/img/001-users.png",
  ADS: IMAGE_URL + "/img/003-ads.png",
  OFFICE: IMAGE_URL + "/img/004-office.png",
  BAR_CHART: IMAGE_URL + "/img/002-bar-chart.png",
  PIGGY: IMAGE_URL + "/img/004-piggy-bank.png",
  ANALYSIS: IMAGE_URL + "/img/001-analysis.png",
  BUSINESS_PLAN: IMAGE_URL + "/img/006-business-plan.png",
  FACE_1: IMAGE_URL + "/img/icon-face-1jpg.jpg",
  ICON_RIGHT: IMAGE_URL + "/img/avataradmin.png",
  LOGO_FOOTER: IMAGE_URL + "/img/logo_footer.png",
  IMG_ROOM: IMAGE_URL + "/img/ads-3-min.png",
  IMG_ROOM_1: IMAGE_URL + "/img/ads-4-min.png",
  IMG_ROOM_2: IMAGE_URL + "/img/img_room.jpg",
  DETAIL_ROOM: IMAGE_URL + "/img/detairoom.jpg",
  AVATAR_USER: IMAGE_URL + "/img/avatar.png",
  COTON: IMAGE_URL + "/img/dribbble_1.gif",
  FACE_2: IMAGE_URL + "/img/client-nguyen-van-thanh-80x80.jpg",
  FACE_3: IMAGE_URL + "/img/2-150x150.jpg",
};